language: python
python:
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: pytest tests
services:
  - mysql
before_install:
  - mysqladmin -uroot create hakoblog_test
  - sh -c 'cat db/schema.sql | mysql -uroot hakoblog_test'
